"""
run_pipeline.py: Main entry point for the CNA Scorecard data pipeline.
"""
from ingest import load_cve_records, load_cna_list
from scoring import score_cve_record
from completeness import compute_field_utilization
from aggregation import aggregate_cna_scores
from trend import calculate_monthly_trend, summarize_trend
from sync_cna_list import sync_cna_list
from output import write_json

# Canonical field list with importance and description
# Only include CNA-controlled fields in completeness analysis
# Exclude true metadata fields that are auto-generated by CVE system
CANONICAL_FIELDS = [
    # Core required fields
    {"field": "containers.cna.descriptions", "importance": "High", "description": "Vulnerability descriptions"},
    {"field": "containers.cna.affected", "importance": "High", "description": "Affected products and versions"},
    {"field": "containers.cna.references", "importance": "High", "description": "Patch Info URLs and documentation"},
    {"field": "containers.cna.problemTypes", "importance": "High", "description": "Problem type information (CWE, etc.)"},
    {"field": "containers.cna.metrics", "importance": "High", "description": "Impact metrics (CVSS scores)"},
    
    # Important descriptive fields
    {"field": "descriptions.english", "importance": "Medium", "description": "At least one English description"},
    {"field": "affected.vendor", "importance": "Medium", "description": "Vendor information in affected products"},
    {"field": "affected.product", "importance": "Medium", "description": "Product information in affected products"},
    {"field": "affected.versions", "importance": "Medium", "description": "Version information"},
    {"field": "containers.cna.title", "importance": "Medium", "description": "Brief title or headline"},
    {"field": "problemTypes.type", "importance": "Medium", "description": "Problem type classification"},
    {"field": "problemTypes.cwe", "importance": "Medium", "description": "Common Weakness Enumeration identifiers"},
    
    # CVSS and metrics
    {"field": "metrics.cvssV3_1", "importance": "Medium", "description": "CVSS v3.1 metrics"},
    {"field": "metrics.cvssV4", "importance": "Medium", "description": "CVSS v4.0 metrics"},
    {"field": "metrics.cvssV3_0", "importance": "Medium", "description": "CVSS v3.0 metrics"},
    {"field": "metrics.cvssV2", "importance": "Medium", "description": "CVSS v2.0 metrics"},
    {"field": "metrics.scenarios", "importance": "Medium", "description": "Metric scenarios"},
    {"field": "metrics.other", "importance": "Medium", "description": "Other metric formats"},
    
    # Reference types
    {"field": "references.named", "importance": "Medium", "description": "Named references"},
    {"field": "references.advisory", "importance": "Medium", "description": "Advisory references"},
    {"field": "references.exploit", "importance": "Medium", "description": "Exploit references"},
    {"field": "references.technical", "importance": "Medium", "description": "Technical references"},
    {"field": "references.vendor", "importance": "Medium", "description": "Vendor references"},
    {"field": "references.patch", "importance": "Medium", "description": "Patch references"},
    
    # Affected product details
    {"field": "affected.defaultStatus", "importance": "Medium", "description": "Default vulnerability status"},
    {"field": "affected.cpes", "importance": "Medium", "description": "Common Platform Enumeration identifiers"},
    {"field": "affected.platforms", "importance": "Medium", "description": "Affected platforms"},
    {"field": "affected.modules", "importance": "Medium", "description": "Affected modules or components"},
    {"field": "affected.programFiles", "importance": "Medium", "description": "Affected source code files"},
    {"field": "affected.programRoutines", "importance": "Medium", "description": "Affected functions or methods"},
    {"field": "affected.repo", "importance": "Medium", "description": "Source code repository URL"},
    
    # Additional CNA-provided content
    {"field": "containers.cna.impacts", "importance": "Medium", "description": "Impact descriptions"},
    {"field": "containers.cna.solutions", "importance": "Medium", "description": "Solutions and remediations"},
    {"field": "containers.cna.workarounds", "importance": "Medium", "description": "Workarounds and mitigations"},
    {"field": "containers.cna.exploits", "importance": "Medium", "description": "Information about known exploits"},
    {"field": "containers.cna.configurations", "importance": "Medium", "description": "Required configurations for exploitation"},
    {"field": "containers.cna.timeline", "importance": "Medium", "description": "Timeline of significant events"},
    {"field": "containers.cna.credits", "importance": "Medium", "description": "Credits and acknowledgments"},
    {"field": "containers.cna.source", "importance": "Medium", "description": "Source information"},
    {"field": "containers.cna.cpeApplicability", "importance": "Medium", "description": "CPE applicability information"},
    {"field": "containers.cna.taxonomyMappings", "importance": "Low", "description": "Mappings to security taxonomies"},
    {"field": "containers.cna.tags", "importance": "Low", "description": "CNA-provided tags"},
    {"field": "containers.cna.datePublic", "importance": "Low", "description": "Date the vulnerability was disclosed publicly"},
    {"field": "containers.cna.dateAssigned", "importance": "Low", "description": "Date the CVE ID was assigned"},
    
    # Enhanced descriptions
    {"field": "descriptions.multipleLanguages", "importance": "Low", "description": "Multiple language descriptions"},
    {"field": "descriptions.supportingMedia", "importance": "Low", "description": "Supporting media (diagrams, etc.)"},
    {"field": "problemTypes.references", "importance": "Low", "description": "Problem type references"},
    
    # Note: containers.adp is excluded as it's controlled by ADPs, not CNAs
]

FIELD_LIST = [f["field"] for f in CANONICAL_FIELDS]

from datetime import datetime, timedelta
import os

def generate_individual_cna_jsons(cve_records, cna_scorecards, cna_summary, cna_metadata=None, trend_periods=None):
    """Generate individual CNA JSON files matching the deployed format.
    
    Args:
        cve_records: List of CVE records
        cna_scorecards: Dictionary of CNA scorecards
        cna_summary: List of CNA summary data
        cna_metadata: Dictionary of rich CNA metadata (organizationName, scope, etc.)
        trend_periods: Dictionary with current and previous period date ranges for trend analysis
    """
    from collections import defaultdict
    import re
    
    def sanitize_filename(name):
        """Sanitize filename by replacing invalid characters."""
        # Replace invalid characters with underscores
        sanitized = re.sub(r'[<>:"/\|?*]', '_', name)
        # Remove multiple consecutive underscores
        sanitized = re.sub(r'_{2,}', '_', sanitized)
        # Remove leading/trailing underscores
        sanitized = sanitized.strip('_')
        return sanitized
    
    # Filter CVEs for the last 6 months
    cutoff_date = datetime.now() - timedelta(days=183)  # ~6 months
    
    def filter_cves_by_period(cve_scores, start_date, end_date):
        """Filter CVEs to only include those within a specific date range."""
        filtered_cves = []
        for cve in cve_scores:
            # Look for datePublished in the correct CVE metadata location
            date_published = cve.get('cveMetadata', {}).get('datePublished', '')
            if date_published:
                try:
                    if 'T' in date_published:
                        pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00')).date()
                    else:
                        pub_date = datetime.strptime(date_published, '%Y-%m-%d').date()
                    
                    # Convert start_date and end_date to date objects for comparison
                    start_date_obj = start_date.date() if hasattr(start_date, 'date') else start_date
                    end_date_obj = end_date.date() if hasattr(end_date, 'date') else end_date
                    
                    if start_date_obj <= pub_date <= end_date_obj:
                        filtered_cves.append(cve)
                except (ValueError, TypeError):
                    # Skip CVEs with unparseable dates for trend analysis
                    continue
        return filtered_cves
    
    def calculate_trend_analysis(current_cves, previous_cves):
        """Calculate trend by comparing current vs previous period performance."""
        if not current_cves and not previous_cves:
            return "steady", "No data available for trend analysis"
        
        # Calculate average scores for each period
        def get_avg_score(cves):
            if not cves:
                return 0
            scores = [cve.get('totalScore', 0) for cve in cves if cve.get('totalScore') is not None]
            return sum(scores) / len(scores) if scores else 0
        
        current_avg = get_avg_score(current_cves)
        previous_avg = get_avg_score(previous_cves)
        
        # Determine trend based on score comparison
        if previous_avg == 0 and current_avg > 0:
            return "improving", f"New activity with {current_avg:.1f}% average score"
        elif current_avg == 0 and previous_avg > 0:
            return "declining", "No recent activity"
        elif previous_avg == 0 and current_avg == 0:
            return "steady", "No activity in either period"
        
        score_diff = current_avg - previous_avg
        
        if score_diff > 5:  # Improvement threshold
            return "improving", f"Score improved by {score_diff:.1f} points"
        elif score_diff < -5:  # Decline threshold
            return "declining", f"Score declined by {abs(score_diff):.1f} points"
        else:
            return "steady", f"Score stable at {current_avg:.1f}%"
    
    # Create ranking map from CNA summary
    ranking_map = {}
    total_cnas = len(cna_summary)
    for idx, cna in enumerate(cna_summary):
        short_name = cna.get('shortName', '')
        if short_name:
            ranking_map[short_name] = {
                'rank': idx + 1,
                'active_cna_count': total_cnas,
                'percentile': round(((total_cnas - idx) / total_cnas) * 100, 1)
            }
    
    # Group CVEs by CNA - extract CNA info from CVE structure
    cna_cves = defaultdict(list)
    for cve in cve_records:
        # Try to get assigningCna field first (if already set)
        assigning_cna = cve.get('assigningCna', '')
        
        # If not set, extract from CVE structure
        if not assigning_cna:
            containers = cve.get('containers', {})
            cna_container = containers.get('cna', {})
            provider = cna_container.get('providerMetadata', {})
            assigning_cna = provider.get('shortName', '')
        
        if assigning_cna:
            # Set the assigningCna field for later use
            cve['assigningCna'] = assigning_cna
            cna_cves[assigning_cna].append(cve)
    
    # Ensure output directory exists
    output_dir = os.path.join(os.path.dirname(__file__), "..", "web", "data", "cna")
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"\nGenerating individual CNA JSON files...")
    generated_count = 0
    
    # Diagnostic: print CNA keys and CVE counts
    print(f"cna_scorecards keys: {list(cna_scorecards.keys())}")
    print(f"cna_cves keys: {list(cna_cves.keys())}")
    for k in cna_cves:
        print(f"CNA {k} has {len(cna_cves[k])} CVEs")
    # Generate individual JSON files for each CNA
    for cna_id, scorecard in cna_scorecards.items():
        cna_info = scorecard.get('cna_info', [{}])
        if isinstance(cna_info, list):
            cna_info = cna_info[0] if cna_info else {}
        short_name = cna_info.get('cna', '') or cna_info.get('shortName', '')
        if not short_name:
            print(f"Skipping CNA due to missing short_name in scorecard: {scorecard}")
            continue
        
        # Get CVE data for this CNA and perform trend analysis
        cna_cve_data = cna_cves.get(short_name, [])
        
        # Debug: Print info for first few CNAs
        if generated_count < 3:
            print(f"    Debug {short_name}: Found {len(cna_cve_data)} total CVEs for this CNA")
        
        # Filter CVEs for current and previous periods for trend analysis
        if trend_periods:
            current_period_cves = filter_cves_by_period(
                cna_cve_data, 
                trend_periods['current_start'], 
                trend_periods['current_end']
            )
            
            # Debug: Print filtering results for first few CNAs
            if generated_count < 3:
                print(f"    Debug {short_name}: Filtered to {len(current_period_cves)} current period CVEs")
                if len(current_period_cves) > 0:
                    sample_cve = current_period_cves[0]
                    print(f"    Debug {short_name}: Sample CVE date: {sample_cve.get('cveMetadata', {}).get('datePublished', 'No date')}")
            previous_period_cves = filter_cves_by_period(
                cna_cve_data, 
                trend_periods['previous_start'], 
                trend_periods['previous_end']
            )
            
            # Calculate trend analysis
            trend_direction, trend_description = calculate_trend_analysis(current_period_cves, previous_period_cves)
            
            # Use current period CVEs as "recent" CVEs for display - score and format them properly
            recent_cves = []
            for cve in current_period_cves:
                try:
                    # Score the CVE record
                    scored_cve = score_cve_record(cve)
                    
                    # Create clean scored format
                    clean_cve = {
                        "cveId": cve.get("cveMetadata", {}).get("cveId", ""),
                        "assigningCna": cve.get("assigningCna", short_name),
                        "datePublished": cve.get("cveMetadata", {}).get("datePublished", ""),
                        "totalCveScore": scored_cve.get("totalScore", 0),
                        "scoreBreakdown": {
                            "foundationalCompleteness": scored_cve.get("foundationalCompleteness", 0),
                            "rootCauseAnalysis": scored_cve.get("rootCauseAnalysis", 0),
                            "softwareIdentification": scored_cve.get("softwareIdentification", 0),
                            "severityAndImpactContext": scored_cve.get("severityAndImpactContext", 0),
                            "patchinfo": scored_cve.get("patchinfo", 0)
                        }
                    }
                    recent_cves.append(clean_cve)
                except Exception as e:
                    # Skip CVEs that can't be scored
                    continue
        else:
            # Fallback to old logic if trend_periods not provided
            cutoff_date = datetime.now() - timedelta(days=183)
            recent_cves = []
            for cve in cna_cve_data:
                date_published = cve.get('datePublished', '')
                if date_published:
                    try:
                        if 'T' in date_published:
                            pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00'))
                        else:
                            pub_date = datetime.strptime(date_published, '%Y-%m-%d')
                        if pub_date >= cutoff_date:
                            # Score and format the CVE properly
                            try:
                                scored_cve = score_cve_record(cve)
                                clean_cve = {
                                    "cveId": cve.get("cveMetadata", {}).get("cveId", ""),
                                    "assigningCna": cve.get("assigningCna", short_name),
                                    "datePublished": date_published,
                                    "totalCveScore": scored_cve.get("totalScore", 0),
                                    "scoreBreakdown": {
                                        "foundationalCompleteness": scored_cve.get("foundationalCompleteness", 0),
                                        "rootCauseAnalysis": scored_cve.get("rootCauseAnalysis", 0),
                                        "softwareIdentification": scored_cve.get("softwareIdentification", 0),
                                        "severityAndImpactContext": scored_cve.get("severityAndImpactContext", 0),
                                        "patchinfo": scored_cve.get("patchinfo", 0)
                                    }
                                }
                                recent_cves.append(clean_cve)
                            except Exception:
                                # Skip CVEs that can't be scored
                                continue
                    except (ValueError, TypeError):
                        # Skip CVEs with invalid dates
                        continue
            trend_direction = "steady"
            trend_description = "Trend analysis not available"
        
        # Get ranking information
        ranking_info = ranking_map.get(short_name, {
            'rank': 999,
            'active_cna_count': 1,
            'percentile': 0.0
        })
        
        # Map category names to deployed format
        category_breakdown = scorecard.get('categoryBreakdown', {})
        
        # Get rich metadata for this CNA if available
        metadata = {}
        if cna_metadata:
            # Find metadata by cna_id or short_name
            for cna_id, meta in cna_metadata.items():
                if meta.get('shortName') == short_name:
                    metadata = meta
                    break
        
        # Extract enhanced metadata fields (using correct field names from generate_cna_scorecards)
        rich_metadata = {}
        if metadata:
            rich_metadata = {
                'organizationName': metadata.get('organizationName', short_name),
                'scope': metadata.get('scope', ''),
                'advisories': metadata.get('advisories', []),
                'email': metadata.get('email', []),
                # Use 'cnaID' from metadata for 'officialCnaID', and 'type' for 'cnaTypes'
                'officialCnaID': metadata.get('cnaID', ''),
                'cnaTypes': metadata.get('type', []),
                'country': metadata.get('country', ''),
                'disclosurePolicy': metadata.get('disclosurePolicy', []),
                'rootCnaInfo': metadata.get('rootCnaInfo', {})
            }
        else:
            # Fallback metadata if no official data found
            rich_metadata = {
                'organizationName': short_name,
                'scope': '',
                'advisories': [],
                'email': [],
                'officialCnaID': '',  # Will be set below if present in metadata
                'cnaTypes': [],       # Will be set below if present in metadata
                'country': '',
                'disclosurePolicy': [],
                'rootCnaInfo': {}
            }
            # Map cnaID/type from metadata to officialCnaID/cnaTypes
            if rich_metadata:
                if 'cnaID' in rich_metadata:
                    rich_metadata['officialCnaID'] = rich_metadata['cnaID']
                if 'type' in rich_metadata:
                    rich_metadata['cnaTypes'] = rich_metadata['type']

        
        # Extract proper CNA scoring from aggregation (scorecard['cna_scoring'][0])
        cna_scoring_list = scorecard.get('cna_scoring', [])
        cna_scoring_dict = cna_scoring_list[0] if cna_scoring_list else {}
        # Defensive fallback for trend fields
        cna_scoring_dict['trend_direction'] = trend_direction
        cna_scoring_dict['trend_description'] = trend_description
        cna_scoring = [cna_scoring_dict]

        # Ensure each CVE in recent_cves/cve_scoring is scored with actual values
        scored_recent_cves = []
        for cve in current_period_cves:
            try:
                scored_cve = score_cve_record(cve)
                clean_cve = {
                    "cveId": scored_cve.get("cveId", ""),
                    "assigningCna": scored_cve.get("assigningCna", short_name),
                    "datePublished": scored_cve.get("datePublished", ""),
                    "totalCveScore": scored_cve.get("totalScore", 0),
                    "scoreBreakdown": scored_cve.get("scoreBreakdown", {})
                }
                scored_recent_cves.append(clean_cve)
            except Exception as e:
                print(f"Failed to score CVE in {short_name}: {e}")
                continue

        # Create individual CNA JSON with enhanced metadata
        cna_json = {
            'cna_info': {
                'cna': short_name,
                'total_cves': cna_scoring_dict.get('total_cves', 0),
                'total_cves_scored': cna_scoring_dict.get('total_cves_scored', 0),
                # Enhanced metadata from pipeline
                **rich_metadata,
            },
            # Trend analysis results
            'trend_direction': trend_direction,
            'trend_description': trend_description,
            **ranking_info,
            'cna_scoring': cna_scoring,
            'recent_cves': scored_recent_cves,
            'cve_scoring': scored_recent_cves  # Only include recent CVEs in cve_scoring as well
        }
        
        # Write to file with sanitized filename
        safe_filename = sanitize_filename(short_name)
        output_file = os.path.join(output_dir, f"{safe_filename}.json")
        print(f"Attempting to write CNA JSON for {short_name} to {output_file} with {len(recent_cves)} recent CVEs")
        try:
            with open(output_file, 'w') as f:
                import json
                json.dump(cna_json, f, indent=2)
        except Exception as e:
            print(f"Failed to write {output_file}: {e}")
        
        generated_count += 1
        
        # Print progress for first few CNAs
        if generated_count <= 5:
            print(f"  Generated {short_name}.json - {cna_json['cna_info']['total_cves']} CVEs, {len(recent_cves)} recent")
    
    print(f"Generated {generated_count} individual CNA JSON files in {output_dir}")
    return generated_count

def main():
    # Sync CNAs list to ensure latest data
    print("Syncing CNAs list from official CVE Project repository...")
    sync_success = sync_cna_list()
    if not sync_success:
        print("Warning: CNAs list sync failed, continuing with existing data")
    
    # Load CVE data for last 6 months for scorecard calculations (original methodology)
    print("Loading CVE data for last 6 months for scorecard calculations...")
    cve_records = load_cve_records()
    
    # Filter to last 6 months for scoring (restore original logic)
    from datetime import timezone
    today = datetime.now(timezone.utc).date()
    six_months_ago = today - timedelta(days=183)
    
    # Filter CVE records to last 6 months for scoring
    filtered_cve_records = []
    for cve in cve_records:
        date_published = cve.get('datePublished', '') or cve.get('cveMetadata', {}).get('datePublished', '')
        if date_published:
            try:
                if 'T' in date_published:
                    pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00')).date()
                else:
                    pub_date = datetime.strptime(date_published, '%Y-%m-%d').date()
                if pub_date >= six_months_ago:
                    filtered_cve_records.append(cve)
            except (ValueError, TypeError):
                # Exclude CVEs with unparseable dates from recent_cves
                continue
        # Exclude CVEs without datePublished from recent_cves
    print(f"Strictly filtered {len(filtered_cve_records)} CVEs from last 6 months for scoring (from {len(cve_records)} total)")
    
    print(f"Filtered {len(filtered_cve_records)} CVEs from last 6 months for scoring (from {len(cve_records)} total)")
    cna_list = load_cna_list(filtered_cve_records)
    
    # Calculate date ranges for trend analysis (12 months total)
    from datetime import timezone
    today = datetime.now(timezone.utc).date()
    
    # Current 6-month period (last 183 days from today)
    current_end_date = today
    current_start_date = (today - timedelta(days=183))  # ~6 months
    
    current_start_str = current_start_date.strftime('%Y-%m-%d')
    current_end_str = current_end_date.strftime('%Y-%m-%d')
    
    print(f"Trend analysis period:")
    print(f"  Current period: {current_start_str} to {current_end_str}")
    
    # Score all filtered CVEs
    scored = [score_cve_record(cve) for cve in filtered_cve_records]
    print(f"Scored {len(scored)} CVEs from last 6 months")

    # Aggregate by CNA using new aggregation module
    periods = [
        (datetime.combine(current_start_date, datetime.min.time()), datetime.combine(current_end_date, datetime.min.time())),
    ]
    cna_outputs = aggregate_cna_scores(scored, periods)

    # Prepare trend periods for generate_individual_cna_jsons
    previous_start_date = current_start_date - timedelta(days=183)
    previous_end_date = current_start_date - timedelta(days=1)
    trend_periods = {
        'current_start': current_start_date,
        'current_end': current_end_date,
        'previous_start': previous_start_date,
        'previous_end': previous_end_date
    }

    # Load CNA metadata if available
    cna_metadata = None
    cna_metadata_path = os.path.join(os.path.dirname(__file__), '..', 'web', 'data', 'cna_list.json')
    if os.path.exists(cna_metadata_path):
        import json
        with open(cna_metadata_path, 'r') as f:
            cna_metadata = {meta.get('shortName'): meta for meta in json.load(f) if meta.get('shortName')}

    # Generate all CNA JSON files with proper date filtering
    from run_pipeline import generate_individual_cna_jsons
    generate_individual_cna_jsons(
        cve_records=filtered_cve_records,
        cna_scorecards=cna_outputs,
        cna_summary=[{'shortName': k, **v['cna_info'][0]} for k, v in cna_outputs.items()],
        cna_metadata=cna_metadata,
        trend_periods=trend_periods
    )

    print(f"Generated individual CNA JSON files in {os.path.join(os.path.dirname(__file__), '..', 'web', 'data', 'cna')}")

    # Write summary card info (as before)
    summary = {
        "analysis_period_start": current_start_str,
        "analysis_period_end": current_end_str,
        "cve_count": len(cve_records),
        "cna_count": len(cna_outputs)
    }
    write_json(summary, "completeness_summary.json")
    print(f"\nPipeline completed successfully!")
    print(f"Generated {len(cna_outputs)} CNA JSON files and summary.")

if __name__ == "__main__":
    main()
