"""
run_pipeline.py: Main entry point for the CNA Scorecard data pipeline.
"""
import json
import os
from ingest import load_cve_records, load_cna_list
from scoring import score_cve_record
from completeness import compute_field_utilization, compute_individual_cna_field_utilization
from aggregation import aggregate_cna_scores
from trend import calculate_monthly_trend, summarize_trend
from sync_cna_list import sync_cna_list
from output import write_json

# Canonical field list with importance and description
# Only include CNA-controlled fields in completeness analysis
# Exclude true metadata fields that are auto-generated by CVE system
# CNA ScoreCard measured fields mapping
CNA_SCORECARD_FIELDS = {
    # Foundational Completeness (50% weight)
    'containers.cna.descriptions': 'foundationalCompleteness',

    'containers.cna.affected': 'foundationalCompleteness',
    'containers.cna.references': 'foundationalCompleteness',
    
    # Root Cause Analysis (15% weight)
    'problemTypes.cwe': 'rootCauseAnalysis',

    
    # Severity and Impact Context (15% weight)
    'metrics.cvssV3_0': 'severityAndImpactContext',
    'metrics.cvssV3_1': 'severityAndImpactContext',
    'metrics.cvssV4_0': 'severityAndImpactContext',
    
    # Software Identification (10% weight)
    'affected.cpes': 'softwareIdentification',
    
    # Patch Information (10% weight)
    'references.patch': 'patchinfo',
}

CANONICAL_FIELDS = [
    # CNA ScoreCard Measured Fields (High-Level Criteria Only)
    {"field": "containers.cna.descriptions", "importance": "High", "description": "Vulnerability descriptions", "cna_scorecard_category": "foundationalCompleteness"},
    {"field": "containers.cna.affected", "importance": "High", "description": "Affected products and versions", "cna_scorecard_category": "foundationalCompleteness"},
    {"field": "containers.cna.references", "importance": "High", "description": "Patch Info URLs and documentation", "cna_scorecard_category": "foundationalCompleteness"},
    {"field": "problemTypes.cwe", "importance": "High", "description": "Common Weakness Enumeration identifiers", "cna_scorecard_category": "rootCauseAnalysis"},
    {"field": "metrics.cvssV3_1", "importance": "High", "description": "CVSS v3.1 metrics", "cna_scorecard_category": "severityAndImpactContext"},
    {"field": "metrics.cvssV3_0", "importance": "High", "description": "CVSS v3.0 metrics", "cna_scorecard_category": "severityAndImpactContext"},
    {"field": "metrics.cvssV4_0", "importance": "High", "description": "CVSS v4.0 metrics", "cna_scorecard_category": "severityAndImpactContext"},
    {"field": "affected.cpes", "importance": "High", "description": "Common Platform Enumeration identifiers", "cna_scorecard_category": "softwareIdentification"},
    {"field": "references.patch", "importance": "High", "description": "Patch references", "cna_scorecard_category": "patchinfo"},
    
    # Non-measured fields (no cna_scorecard_category)
    {"field": "descriptions.english", "importance": "Medium", "description": "At least one English description"},
    {"field": "affected.vendor", "importance": "Medium", "description": "Vendor information in affected products"},
    {"field": "affected.product", "importance": "Medium", "description": "Product information in affected products"},
    {"field": "affected.versions", "importance": "Medium", "description": "Version information"},
    {"field": "containers.cna.title", "importance": "Medium", "description": "Brief title or headline"},
    {"field": "problemTypes.type", "importance": "Medium", "description": "Problem type classification"},
    {"field": "containers.cna.problemTypes", "importance": "High", "description": "Problem type information (CWE, etc.)"},
    
    # CVSS and metrics (non-measured - cvssV3_0, cvssV3_1, cvssV4 are measured above)
    {"field": "metrics.cvssV2_0", "importance": "Medium", "description": "CVSS v2.0 metrics"},
    {"field": "metrics.scenarios", "importance": "Medium", "description": "Metric scenarios"},
    {"field": "metrics.other", "importance": "Medium", "description": "Other metric formats"},
    {"field": "containers.cna.metrics", "importance": "High", "description": "Impact metrics (CVSS scores)"},
    
    # Reference types (non-measured - only patch/advisory are measured above)
    {"field": "references.named", "importance": "Medium", "description": "Named references"},
    {"field": "references.exploit", "importance": "Medium", "description": "Exploit references"},
    {"field": "references.technical", "importance": "Medium", "description": "Technical references"},
    {"field": "references.vendor", "importance": "Medium", "description": "Vendor references"},
    {"field": "references.advisory", "importance": "Medium", "description": "Advisory references"},
    
    # Affected product details (non-measured - only affected.cpes is measured above)
    {"field": "affected.defaultStatus", "importance": "Medium", "description": "Default vulnerability status"},
    {"field": "affected.platforms", "importance": "Medium", "description": "Affected platforms"},
    {"field": "affected.modules", "importance": "Medium", "description": "Affected modules or components"},
    {"field": "affected.programFiles", "importance": "Medium", "description": "Affected source code files"},
    {"field": "affected.programRoutines", "importance": "Medium", "description": "Affected functions or methods"},
    {"field": "affected.repo", "importance": "Medium", "description": "Source code repository URL"},
    
    # Additional CNA-provided content
    {"field": "containers.cna.impacts", "importance": "Medium", "description": "Impact descriptions"},
    {"field": "containers.cna.solutions", "importance": "Medium", "description": "Solutions and remediations"},
    {"field": "containers.cna.workarounds", "importance": "Medium", "description": "Workarounds and mitigations"},
    {"field": "containers.cna.exploits", "importance": "Medium", "description": "Information about known exploits"},
    {"field": "containers.cna.configurations", "importance": "Medium", "description": "Required configurations for exploitation"},
    {"field": "containers.cna.timeline", "importance": "Medium", "description": "Timeline of significant events"},
    {"field": "containers.cna.credits", "importance": "Medium", "description": "Credits and acknowledgments"},
    {"field": "containers.cna.source", "importance": "Medium", "description": "Source information"},
    {"field": "containers.cna.cpeApplicability", "importance": "Medium", "description": "CPE applicability information"},
    {"field": "containers.cna.taxonomyMappings", "importance": "Low", "description": "Mappings to security taxonomies"},
    {"field": "containers.cna.tags", "importance": "Low", "description": "CNA-provided tags"},
    {"field": "containers.cna.datePublic", "importance": "Low", "description": "Date the vulnerability was disclosed publicly"},
    {"field": "containers.cna.dateAssigned", "importance": "Low", "description": "Date the CVE ID was assigned"},
    
    # Enhanced descriptions (matching deployed field names) - NOT measured by CNA ScoreCard
    {"field": "descriptions.multiple_languages", "importance": "Low", "description": "Multiple language descriptions"},
    {"field": "descriptions.supporting_media", "importance": "Low", "description": "Supporting media (diagrams, etc.)"},
    {"field": "problemTypes.references", "importance": "Low", "description": "Problem type references"},
    
    # ADP Container (included in deployed version)
    {"field": "containers.adp", "importance": "Low", "description": "Authorized Data Publisher container"},
]

FIELD_LIST = [f["field"] for f in CANONICAL_FIELDS]

from datetime import datetime, timedelta
import os
import json

def generate_individual_cna_jsons(cve_records, cna_scorecards, sorted_active_cnas, cna_metadata=None, trend_periods=None):
    """Generate individual CNA JSON files matching the deployed format.
    
    Args:
        cve_records: List of CVE records
        cna_scorecards: Dictionary of CNA scorecards
        sorted_active_cnas: List of active CNA summary data (for ranking calculations)
        cna_metadata: Dictionary of rich CNA metadata (organizationName, scope, etc.)
        trend_periods: Dictionary with current and previous period date ranges for trend analysis
    """
    from collections import defaultdict
    import re
    
    def sanitize_filename(name):
        """Sanitize filename by replacing invalid characters."""
        # Replace invalid characters with underscores
        sanitized = re.sub(r'[<>:"/\|?*]', '_', name)
        # Remove multiple consecutive underscores
        sanitized = re.sub(r'_{2,}', '_', sanitized)
        # Remove leading/trailing underscores
        sanitized = sanitized.strip('_')
        return sanitized
    
    # Filter CVEs for the last 6 months
    cutoff_date = datetime.now() - timedelta(days=183)  # ~6 months
    
    def filter_cves_by_period(cve_scores, start_date, end_date):
        """Filter CVEs to only include those within a specific date range."""
        filtered_cves = []
        for cve in cve_scores:
            # Look for datePublished in the correct CVE metadata location
            date_published = cve.get('cveMetadata', {}).get('datePublished', '')
            if date_published:
                try:
                    if 'T' in date_published:
                        pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00')).date()
                    else:
                        pub_date = datetime.strptime(date_published, '%Y-%m-%d').date()
                    
                    # Convert start_date and end_date to date objects for comparison
                    start_date_obj = start_date.date() if hasattr(start_date, 'date') else start_date
                    end_date_obj = end_date.date() if hasattr(end_date, 'date') else end_date
                    
                    if start_date_obj <= pub_date <= end_date_obj:
                        filtered_cves.append(cve)
                except (ValueError, TypeError):
                    # Skip CVEs with unparseable dates for trend analysis
                    continue
        return filtered_cves
    
    def calculate_trend_analysis(current_cves, previous_cves):
        """Calculate trend by comparing current vs previous period performance.
        Uses improved algorithm with lower thresholds (2.0 instead of 5.0) and
        better tooltip-friendly descriptions.
        """
        print(f"\n[DEBUG] calculate_trend_analysis called with {len(current_cves)} current CVEs and {len(previous_cves)} previous CVEs")
        if not current_cves and not previous_cves:
            print("[DEBUG] No CVEs in either period")
            return "steady", "➡️ No data"
        
        # Calculate average scores for each period
        def get_avg_score(cves):
            if not cves:
                return 0
            # Handle both totalScore and totalCveScore fields
            scores = []
            for cve in cves:
                score = cve.get('totalCveScore') or cve.get('totalScore', 0)
                if score is not None and score > 0:
                    scores.append(score)
            return sum(scores) / len(scores) if scores else 0
        
        current_avg = get_avg_score(current_cves)
        previous_avg = get_avg_score(previous_cves)
        
        # Determine trend based on score comparison with improved thresholds
        if previous_avg == 0 and current_avg > 0:
            return "improving", f"↗️ New activity: {current_avg:.1f}%"
        elif current_avg == 0 and previous_avg > 0:
            return "declining", "↘️ No recent activity"
        elif previous_avg == 0 and current_avg == 0:
            return "steady", "➡️ No activity"
        
        score_diff = round(current_avg - previous_avg, 2)
        
        if score_diff > 2.0:  # Lowered improvement threshold (was 5.0)
            return "improving", f"↗️ Up {score_diff:.1f} pts"
        elif score_diff < -2.0:  # Lowered decline threshold (was -5.0)
            return "declining", f"↘️ Down {abs(score_diff):.1f} pts"
        else:
            return "steady", f"➡️ Stable at {current_avg:.1f}%"
    
    # Create ranking map that allows ties for identical scores and CVE counts
    ranking_map = {}
    total_cnas = len(sorted_active_cnas)  # Use only active CNAs for ranking calculations
    
    print("\nApplying rankings to CNAs with support for ties...")
    print(f"Total CNAs to rank: {total_cnas}")
    
    # Log table header
    print("{:<5} {:<25} {:<10} {:<10} {:<10}".format(
        "Rank", "CNA", "Score", "CVEs", "Percentile"
    ))
    print("-" * 70)
    
    # Group CNAs by identical scores for proper tied ranking
    from collections import defaultdict
    score_groups = defaultdict(list)
    
    # Group all active CNAs by their overall_average_score
    for cna in sorted_active_cnas:
        score = cna.get('overall_average_score', 0)
        score_groups[score].append(cna)
    
    # Sort score groups by score (descending) and create tied groups
    tied_groups = []
    for score in sorted(score_groups.keys(), reverse=True):
        group = score_groups[score]
        # Sort CNAs within each score group by CVE count (descending) for consistent ordering
        group.sort(key=lambda x: x.get('total_cves', 0), reverse=True)
        tied_groups.append(group)
    
    # Second pass: Assign ranks to each group with ties
    next_rank = 1
    for group in tied_groups:
        # All CNAs in this group get the same rank
        group_rank = next_rank
        
        # Calculate percentile based on rank position
        # Lower rank number = better performance = higher percentile
        # Higher rank number = worse performance = lower percentile
        percentile = round(((total_cnas - group_rank + 1) / total_cnas) * 100, 1)
        
        # Apply the rank to all CNAs in this group
        for cna in group:
            short_name = cna.get('shortName', '')
            if not short_name:
                print(f"WARNING: CNA has no shortName! Skipping.")
                continue
            
            # Store the ranking information for this CNA
            ranking_map[short_name] = {
                'rank': group_rank,
                'active_cna_count': total_cnas,  # Use actual active CNA count
                'percentile': percentile
            }
            
            # Log rank information for each CNA
            score = cna.get('overall_average_score', 0)
            cve_count = cna.get('total_cves', 0)
            
            # Only print the first few entries and key CNAs for brevity
            if next_rank <= 10 or short_name in ["ProgressSoftware", "mitre", "debian", "Linux"]:
                print("{:<5} {:<25} {:<10.2f} {:<10} {:<10.1f}".format(
                    group_rank, 
                    short_name[:25], 
                    score,
                    cve_count, 
                    percentile
                ))
                
        # Skip ranks based on the size of the group
        # If 2 CNAs tied for rank 5, the next rank should be 7
        next_rank += len(group)
        
        # This old verification code is now handled in the ranking loop above
    
    # Ensure ProgressSoftware ranking is being properly tracked
    progress_rank = ranking_map.get('ProgressSoftware', {}).get('rank', 'Not found')
    print(f"\nVerification - ProgressSoftware rank: {progress_rank}")
    
    # Count how many CNAs got assigned rankings
    print(f"Successfully created rankings for {len(ranking_map)} CNAs")
    
    # Group CVEs by CNA - extract CNA info from CVE structure
    cna_cves = defaultdict(list)
    for cve in cve_records:
        # Try to get assigningCna field first (if already set)
        assigning_cna = cve.get('assigningCna', '')
        
        # If not set, extract from CVE structure
        if not assigning_cna:
            containers = cve.get('containers', {})
            cna_container = containers.get('cna', {})
            provider = cna_container.get('providerMetadata', {})
            assigning_cna = provider.get('shortName', '')
        
        if assigning_cna:
            # Set the assigningCna field for later use
            cve['assigningCna'] = assigning_cna
            cna_cves[assigning_cna].append(cve)
    
    # Ensure output directory exists
    output_dir = os.path.join(os.path.dirname(__file__), "..", "web", "data", "cna")
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"\nGenerating individual CNA JSON files...")
    generated_count = 0
    
    # Diagnostic: print CNA keys and CVE counts
    print(f"cna_scorecards keys: {list(cna_scorecards.keys())}")
    print(f"cna_cves keys: {list(cna_cves.keys())}")
    for k in cna_cves:
        print(f"CNA {k} has {len(cna_cves[k])} CVEs")
    # Generate individual JSON files for each CNA
    for cna_id, scorecard in cna_scorecards.items():
        cna_info = scorecard.get('cna_info', [{}])
        if isinstance(cna_info, list):
            cna_info = cna_info[0] if cna_info else {}
        short_name = cna_info.get('cna', '') or cna_info.get('shortName', '')
        if not short_name:
            print(f"Skipping CNA due to missing short_name in scorecard: {scorecard}")
            continue
        
        # Get CVE data for this CNA and perform trend analysis
        cna_cve_data = cna_cves.get(short_name, [])
        
        # Debug: Print info for first few CNAs
        if generated_count < 3:
            print(f"    Debug {short_name}: Found {len(cna_cve_data)} total CVEs for this CNA")
        
        # Filter CVEs for current and previous periods for trend analysis
        if trend_periods:
            current_period_cves = filter_cves_by_period(
                cna_cve_data, 
                trend_periods['current_start'], 
                trend_periods['current_end']
            )
            
            # Debug: Print filtering results for first few CNAs
            if generated_count < 3:
                print(f"    Debug {short_name}: Filtered to {len(current_period_cves)} current period CVEs")
                if len(current_period_cves) > 0:
                    sample_cve = current_period_cves[0]
                    print(f"    Debug {short_name}: Sample CVE date: {sample_cve.get('cveMetadata', {}).get('datePublished', 'No date')}")
            previous_period_cves = filter_cves_by_period(
                cna_cve_data, 
                trend_periods['previous_start'], 
                trend_periods['previous_end']
            )
            
            # Calculate trend analysis using improved_trend.py logic
            from trend import calculate_monthly_trend, summarize_trend
            
            # Debugging output to understand what's being passed to trend calculation
            if short_name in ["ProgressSoftware", "vmware", "Fortinet"]:
                print(f"\n[DEBUG] {short_name} CVE counts: Current period: {len(current_period_cves)}, Previous period: {len(previous_period_cves)}")
                if current_period_cves:
                    sample = current_period_cves[0]
                    print(f"[DEBUG] Sample current period CVE: {sample.get('cveId', 'No ID')}, Score: {sample.get('totalScore', 0)}")
                    
            # Debug the current_period_cves to understand what data is being passed to calculate_monthly_trend
            if short_name in ["ProgressSoftware", "vmware", "Fortinet"]:
                print(f"[DEBUG] {short_name} current_period_cves count: {len(current_period_cves)}")
                # Print the first few CVE records to see their structure
                for i, cve in enumerate(current_period_cves[:3]):
                    print(f"[DEBUG] CVE {i}: ID={cve.get('cveId', 'Unknown')}, Published={cve.get('datePublished', 'Unknown')}, Score={cve.get('totalScore', 0)}")
                # Also print the keys of the first CVE to understand available fields
                if current_period_cves:
                    print(f"[DEBUG] Available fields in CVE: {list(current_period_cves[0].keys())}")
                    
            # Skip the monthly_trends calculation but still use our improved trend algorithm
            # monthly_trends = calculate_monthly_trend(current_period_cves, months=6)
            # Instead, get monthly_trends from the existing scorecard data
            cna_scoring_list = scorecard.get('cna_scoring', [])
            if cna_scoring_list and 'monthly_trends' in cna_scoring_list[0]:
                monthly_trends = cna_scoring_list[0].get('monthly_trends', [])
            else:
                # Fallback if no existing monthly_trends
                monthly_trends = [None] * 6
            
            if short_name in ["ProgressSoftware", "vmware", "Fortinet"]:
                print(f"[DEBUG] {short_name} using existing monthly_trends: {monthly_trends}")
            
            # Then use summarize_trend to determine direction and description
            trend_summary = summarize_trend(monthly_trends)
            
            # Store calculated trend values in variables that will be used consistently throughout the pipeline
            calculated_trend_direction = trend_summary['trend_direction']
            calculated_trend_description = trend_summary['trend_description']
            
            # Override the trend values from other sources with our improved calculation
            trend_direction = calculated_trend_direction
            trend_description = calculated_trend_description
            
            if short_name in ["ProgressSoftware", "vmware", "Fortinet"]:
                print(f"[DEBUG] {short_name} CALCULATED trend: {trend_direction}, {trend_description}")
                print("="*50)
            
            # Use current period CVEs as "recent" CVEs for display - score and format them properly
            recent_cves = []
            for cve in current_period_cves:
                try:
                    # Score the CVE record
                    scored_cve = score_cve_record(cve)
                    
                    # Create clean scored format
                    clean_cve = {
                        "cveId": cve.get("cveMetadata", {}).get("cveId", ""),
                        "assigningCna": cve.get("assigningCna", short_name),
                        "datePublished": cve.get("cveMetadata", {}).get("datePublished", ""),
                        "totalCveScore": scored_cve.get("totalScore", 0),
                        "scoreBreakdown": {
                            "foundationalCompleteness": scored_cve.get("foundationalCompleteness", 0),
                            "rootCauseAnalysis": scored_cve.get("rootCauseAnalysis", 0),
                            "softwareIdentification": scored_cve.get("softwareIdentification", 0),
                            "severityAndImpactContext": scored_cve.get("severityAndImpactContext", 0),
                            "patchinfo": scored_cve.get("patchinfo", 0)
                        }
                    }
                    recent_cves.append(clean_cve)
                except Exception as e:
                    # Skip CVEs that can't be scored
                    continue
        else:
            # Fallback to old logic if trend_periods not provided
            cutoff_date = datetime.now() - timedelta(days=183)
            recent_cves = []
            for cve in cna_cve_data:
                date_published = cve.get('datePublished', '')
                if date_published:
                    try:
                        if 'T' in date_published:
                            pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00'))
                        else:
                            pub_date = datetime.strptime(date_published, '%Y-%m-%d')
                        if pub_date >= cutoff_date:
                            # Score and format the CVE properly
                            try:
                                scored_cve = score_cve_record(cve)
                                clean_cve = {
                                    "cveId": cve.get("cveMetadata", {}).get("cveId", ""),
                                    "assigningCna": cve.get("assigningCna", short_name),
                                    "datePublished": date_published,
                                    "totalCveScore": scored_cve.get("totalScore", 0),
                                    "scoreBreakdown": {
                                        "foundationalCompleteness": scored_cve.get("foundationalCompleteness", 0),
                                        "rootCauseAnalysis": scored_cve.get("rootCauseAnalysis", 0),
                                        "softwareIdentification": scored_cve.get("softwareIdentification", 0),
                                        "severityAndImpactContext": scored_cve.get("severityAndImpactContext", 0),
                                        "patchinfo": scored_cve.get("patchinfo", 0)
                                    }
                                }
                                recent_cves.append(clean_cve)
                            except Exception:
                                # Skip CVEs that can't be scored
                                continue
                    except (ValueError, TypeError):
                        # Skip CVEs with invalid dates
                        continue
            trend_direction = "steady"
            trend_description = "Trend analysis not available"
        
        # Get ranking information
        ranking_info = ranking_map.get(short_name, {
            'rank': 999,
            'active_cna_count': 1,
            'percentile': 0.0
        })
        
        # Map category names to deployed format
        category_breakdown = scorecard.get('categoryBreakdown', {})
        
        # Get rich metadata for this CNA if available
        metadata = {}
        if cna_metadata:
            # Find metadata by cna_id or short_name
            for cna_id, meta in cna_metadata.items():
                if meta.get('shortName') == short_name:
                    metadata = meta
                    break
        
        # Extract enhanced metadata fields (using correct field names from generate_cna_scorecards)
        rich_metadata = {}
        if metadata:
            rich_metadata = {
                'organizationName': metadata.get('organizationName', short_name),
                'scope': metadata.get('scope', ''),
                'advisories': metadata.get('advisories', []),
                'email': metadata.get('email', []),
                # Use 'cnaID' from metadata for 'officialCnaID', and 'type' for 'cnaTypes'
                'officialCnaID': metadata.get('cnaID', ''),
                'cnaTypes': metadata.get('type', []),
                'country': metadata.get('country', ''),
                'disclosurePolicy': metadata.get('disclosurePolicy', []),
                'rootCnaInfo': metadata.get('rootCnaInfo', {})
            }
        else:
            # Fallback metadata if no official data found
            rich_metadata = {
                'organizationName': short_name,
                'scope': '',
                'advisories': [],
                'email': [],
                'officialCnaID': '',  # Will be set below if present in metadata
                'cnaTypes': [],       # Will be set below if present in metadata
                'country': '',
                'disclosurePolicy': [],
                'rootCnaInfo': {}
            }
            # Map cnaID/type from metadata to officialCnaID/cnaTypes
            if rich_metadata:
                if 'cnaID' in rich_metadata:
                    rich_metadata['officialCnaID'] = rich_metadata['cnaID']
                if 'type' in rich_metadata:
                    rich_metadata['cnaTypes'] = rich_metadata['type']

        
        # Extract proper CNA scoring from aggregation (scorecard['cna_scoring'][0])
        cna_scoring_list = scorecard.get('cna_scoring', [])
        cna_scoring_dict = cna_scoring_list[0] if cna_scoring_list else {}
        
        # Always use our calculated trend values from improved_trend.py
        cna_scoring_dict['trend_direction'] = calculated_trend_direction
        cna_scoring_dict['trend_description'] = calculated_trend_description
        
        # DO NOT overwrite the monthly_trends - use the existing data
        # monthly_trends in the scorecard may come from a different source with more reliable data
        
        cna_scoring = [cna_scoring_dict]
        
        # For ProgressSoftware, explicitly log what we're adding to cna_scoring_dict
        if short_name in ["ProgressSoftware", "vmware", "Fortinet"]:
            print(f"[DEBUG] Adding to {short_name} cna_scoring_dict: trend_direction={calculated_trend_direction}, trend_description={calculated_trend_description}")
            print(f"[DEBUG] Monthly trends: {monthly_trends}")

        # Ensure each CVE in recent_cves/cve_scoring is scored with actual values
        scored_recent_cves = []
        for cve in current_period_cves:
            try:
                scored_cve = score_cve_record(cve)
                clean_cve = {
                    "cveId": scored_cve.get("cveId", ""),
                    "assigningCna": scored_cve.get("assigningCna", short_name),
                    "datePublished": scored_cve.get("datePublished", ""),
                    "totalCveScore": scored_cve.get("totalScore", 0),
                    "scoreBreakdown": scored_cve.get("scoreBreakdown", {})
                }
                scored_recent_cves.append(clean_cve)
            except Exception as e:
                print(f"Failed to score CVE in {short_name}: {e}")
                continue

        # Create individual CNA JSON with enhanced metadata
        cna_json = {
            'cna_info': {
                'cna': short_name,
                'total_cves': cna_scoring_dict.get('total_cves', 0),
                'total_cves_scored': cna_scoring_dict.get('total_cves_scored', 0),
                # Enhanced metadata from pipeline
                **rich_metadata,
            },
            # Trend analysis results
            'trend_direction': trend_direction,
            'trend_description': trend_description,
            **ranking_info,
            'cna_scoring': cna_scoring,
            'recent_cves': scored_recent_cves,
            'cve_scoring': scored_recent_cves  # Only include recent CVEs in cve_scoring as well
        }
        
        # Write to file with sanitized filename
        safe_filename = sanitize_filename(short_name)
        output_file = os.path.join(output_dir, f"{safe_filename}.json")
        print(f"Attempting to write CNA JSON for {short_name} to {output_file} with {len(recent_cves)} recent CVEs")
        try:
            with open(output_file, 'w') as f:
                import json
                json.dump(cna_json, f, indent=2)
        except Exception as e:
            print(f"Failed to write {output_file}: {e}")
        
        generated_count += 1
        
        # Print progress for first few CNAs
        if generated_count <= 5:
            print(f"  Generated {short_name}.json - {cna_json['cna_info']['total_cves']} CVEs, {len(recent_cves)} recent")
    
    print(f"Generated {generated_count} individual CNA JSON files in {output_dir}")
    return generated_count, ranking_map

def main():
    # Sync CNAs list to ensure latest data
    print("Syncing CNAs list from official CVE Project repository...")
    sync_success = sync_cna_list()
    if not sync_success:
        print("Warning: CNAs list sync failed, continuing with existing data")
    
    # Load official CNA list as primary source of truth for CNA names
    print("Loading official CNA list as primary source of truth...")
    official_cna_metadata = None
    official_cna_metadata_path = os.path.join(os.path.dirname(__file__), '..', 'web', 'data', 'cna_list.json')
    if os.path.exists(official_cna_metadata_path):
        with open(official_cna_metadata_path, 'r') as f:
            official_cna_list = json.load(f)
            official_cna_metadata = {meta.get('shortName'): meta for meta in official_cna_list if meta.get('shortName')}
            print(f"Loaded {len(official_cna_metadata)} official CNAs from authoritative source")
    else:
        print("Warning: Official CNA list not found, pipeline may produce inconsistent results")
        official_cna_metadata = {}
    
    # Load CVE data for last 6 months for scorecard calculations (original methodology)
    print("Loading CVE data for last 6 months for scorecard calculations...")
    cve_records = load_cve_records()
    
    # Filter to last 6 months for scoring (restore original logic)
    from datetime import timezone
    today = datetime.now(timezone.utc).date()
    six_months_ago = today - timedelta(days=183)
    
    # Filter CVE records to last 6 months for scoring
    filtered_cve_records = []
    for cve in cve_records:
        date_published = cve.get('datePublished', '') or cve.get('cveMetadata', {}).get('datePublished', '')
        if date_published:
            try:
                if 'T' in date_published:
                    pub_date = datetime.fromisoformat(date_published.replace('Z', '+00:00')).date()
                else:
                    pub_date = datetime.strptime(date_published, '%Y-%m-%d').date()
                if pub_date >= six_months_ago:
                    filtered_cve_records.append(cve)
            except (ValueError, TypeError):
                # Exclude CVEs with unparseable dates from recent_cves
                continue
        # Exclude CVEs without datePublished from recent_cves
    print(f"Strictly filtered {len(filtered_cve_records)} CVEs from last 6 months for scoring (from {len(cve_records)} total)")
    
    print(f"Filtered {len(filtered_cve_records)} CVEs from last 6 months for scoring (from {len(cve_records)} total)")
    cna_list = load_cna_list(filtered_cve_records)
    
    # Calculate date ranges for trend analysis (12 months total)
    from datetime import timezone
    today = datetime.now(timezone.utc).date()
    
    # Current 6-month period (last 183 days from today)
    current_end_date = today
    current_start_date = (today - timedelta(days=183))  # ~6 months
    
    current_start_str = current_start_date.strftime('%Y-%m-%d')
    current_end_str = current_end_date.strftime('%Y-%m-%d')
    
    print(f"Trend analysis period:")
    print(f"  Current period: {current_start_str} to {current_end_str}")
    
    # Score all filtered CVEs
    scored = [score_cve_record(cve) for cve in filtered_cve_records]
    print(f"Scored {len(scored)} CVEs from last 6 months")

    # Aggregate by CNA using new aggregation module
    periods = [
        (datetime.combine(current_start_date, datetime.min.time()), datetime.combine(current_end_date, datetime.min.time())),
    ]
    cna_outputs = aggregate_cna_scores(scored, periods)

    # Prepare trend periods for generate_individual_cna_jsons
    previous_start_date = current_start_date - timedelta(days=183)
    previous_end_date = current_start_date - timedelta(days=1)
    trend_periods = {
        'current_start': current_start_date,
        'current_end': current_end_date,
        'previous_start': previous_start_date,
        'previous_end': previous_end_date
    }

    # Load CNA metadata if available
    cna_metadata = None
    cna_metadata_path = os.path.join(os.path.dirname(__file__), '..', 'web', 'data', 'cna_list.json')
    if os.path.exists(cna_metadata_path):
        with open(cna_metadata_path, 'r') as f:
            cna_metadata = {meta.get('shortName'): meta for meta in json.load(f) if meta.get('shortName')}

    # Generate all CNA JSON files with proper date filtering
    # First, create the cna_summary list with all necessary information
    # This collects and formats the data we need for ranking and individual JSON creation
    print("\nPreparing CNA data for ranking...")
    cna_summary = []
    for k, v in cna_outputs.items():
        # Get the CNA info
        cna_info = v['cna_info'][0] if v['cna_info'] else {}
        
        # Get the scoring information including overall_average_score
        cna_scoring = v.get('cna_scoring', [{}])[0] if v.get('cna_scoring') else {}
        
        # Get the score values with safety fallbacks
        overall_score = cna_scoring.get('overall_average_score', 0)
        if not isinstance(overall_score, (int, float)):
            overall_score = 0
            
        total_cves = cna_scoring.get('total_cves', 0)
        if not isinstance(total_cves, (int, float)):
            total_cves = 0
        
        # Create a summary entry with shortName and all relevant scoring metrics
        summary_entry = {
            'shortName': k,
            **cna_info,
            'overall_average_score': overall_score,
            'total_cves': total_cves,
            'recent_cves_count': cna_scoring.get('recent_cves_count', 0),
            # Add detailed category scores for web interface
            'foundational_completeness': cna_scoring.get('average_foundational_completeness', 0),
            'root_cause_analysis': cna_scoring.get('average_root_cause_analysis', 0),
            'software_identification': cna_scoring.get('average_software_identification', 0),
            'severity_and_impact': cna_scoring.get('average_severity_context', 0),
            'patchinfo': cna_scoring.get('average_patchinfo', 0),
            # Add percentage fields for category breakdown
            'percent_foundational_completeness': cna_scoring.get('percent_foundational_completeness', 0),
            'percent_root_cause_analysis': cna_scoring.get('percent_root_cause_analysis', 0),
            'percent_software_identification': cna_scoring.get('percent_software_identification', 0),
            'percent_severity_and_impact': cna_scoring.get('percent_severity_and_impact', 0),
            'percent_patchinfo': cna_scoring.get('percent_patchinfo', 0)
        }
        
        cna_summary.append(summary_entry)
    
    # =========================================================================
    # RANKING ALGORITHM DOCUMENTATION
    # =========================================================================
    # 
    # The CNA ranking system uses a simple, transparent approach that allows ties
    # when CNAs have identical performance metrics. Rankings are determined using
    # the following process:
    #
    # 1. PRIMARY SORT: overall_average_score (DESCENDING)
    #    - Higher quality scores rank better
    #    - This is the main quality metric for CNAs
    #
    # 2. SECONDARY SORT: total_cves (DESCENDING)
    #    - When scores tie, CNAs with more published CVEs rank higher
    #    - Rewards higher volume of quality CVE data
    #
    # 3. TIED RANKING: CNAs with identical scores AND identical CVE counts
    #    receive the same rank number
    #
    # 4. RANK SKIPPING: After tied ranks, the next rank number is skipped
    #    Example: If two CNAs tie for rank 5, the next CNA gets rank 7
    #
    # 5. PERCENTILE CALCULATION: ((total_cnas - rank + 1) / total_cnas) * 100
    #    - Percentile is based on rank position, not array index
    #    - Higher percentile = better relative performance
    #
    # This approach ensures that:
    # - Rankings are primarily based on quality (overall_average_score)
    # - Volume of contribution (total_cves) is considered for ties
    # - CNAs with truly identical metrics receive identical ranks
    # - The ranking system is transparent, fair, and easy to understand
    # =========================================================================
    
    # Prepare data for sorting
    for cna in cna_summary:
        # Set default values for tie-breaking fields if missing
        if 'overall_average_score' not in cna or cna['overall_average_score'] is None:
            cna['overall_average_score'] = 0.0
            
        if 'total_cves' not in cna or cna['total_cves'] is None:
            cna['total_cves'] = 0
    
    # Separate CNAs into active (with recent CVEs) and inactive (no recent CVEs)
    active_cnas = []
    inactive_cnas = []
    
    for cna in cna_summary:
        recent_cves_count = cna.get('recent_cves_count', 0)
        if recent_cves_count > 0:
            active_cnas.append(cna)
        else:
            inactive_cnas.append(cna)
    
    # Sort active CNAs by overall_average_score and total_cves (both descending)
    # This provides consistent ordering within score groups for tie detection
    sorted_active_cnas = sorted(
        active_cnas,
        key=lambda x: (
            x.get('overall_average_score', 0),  # Primary sort by score (higher is better)
            x.get('total_cves', 0)              # Secondary sort by CVE count (higher is better)
        ),
        reverse=True  # Descending order
    )
    
    # Sort inactive CNAs by total_cves (descending) for consistent ordering
    sorted_inactive_cnas = sorted(
        inactive_cnas,
        key=lambda x: x.get('total_cves', 0),
        reverse=True  # Descending order
    )
    
    # Combine: active CNAs first (with rankings), then inactive CNAs (without rankings)
    sorted_cna_summary = sorted_active_cnas + sorted_inactive_cnas
    
    # Print detailed header explaining the sorting criteria
    print("\n" + "=" * 80)
    print("CNA RANKING SYSTEM - ACTIVE vs INACTIVE SEPARATION")
    print("=" * 80)
    print(f"Active CNAs (with recent CVEs): {len(sorted_active_cnas)} - Receive rankings 1-{len(sorted_active_cnas)}")
    print(f"Inactive CNAs (no recent CVEs): {len(sorted_inactive_cnas)} - No rankings assigned")
    print("Active CNA Sort: Overall Average Score → Total CVE Count (descending)")
    print("Inactive CNA Sort: Total CVE Count (descending)")
    print("=" * 80)
    
    # Print first 10 entries with all tie-breaking fields
    print("\nTop 10 CNAs after applying all sorting criteria:")
    print("{:<5} {:<25} {:<10} {:<10} {:<10} {:<10}".format(
        "Rank", "CNA", "Score", "Total CVEs", "Recent CVEs", "Percentile"
    ))
    print("-" * 80)
    for i, cna in enumerate(sorted_cna_summary[:10]):
        print("{:<5} {:<25} {:<10.2f} {:<10} {:<10} {:<10.1f}".format(
            i+1, 
            cna.get('shortName', '')[:25], 
            cna.get('overall_average_score', 0),
            cna.get('total_cves', 0),
            cna.get('recent_cves_count', 0),
            ((len(sorted_cna_summary) - i) / len(sorted_cna_summary)) * 100
        ))
    
    # Print examples of tie-breaking at each level
    print("\n" + "=" * 80)
    print("TIE-BREAKING EXAMPLES")
    print("=" * 80)
    
    # Find examples of ties broken at each level (if they exist)
    score_tie_examples = []
    cve_count_tie_examples = []
    recent_cve_tie_examples = []
    
    # Look through the data to find examples of each type of tie-breaking
    for i in range(len(sorted_cna_summary) - 1):
        cna1 = sorted_cna_summary[i]
        cna2 = sorted_cna_summary[i + 1]
        
        # Same score, different total CVEs
        if (cna1.get('overall_average_score') == cna2.get('overall_average_score') and 
                cna1.get('total_cves') != cna2.get('total_cves')):
            score_tie_examples.append((i, cna1, cna2))
            if len(score_tie_examples) >= 2:
                break
    
    for i in range(len(sorted_cna_summary) - 1):
        cna1 = sorted_cna_summary[i]
        cna2 = sorted_cna_summary[i + 1]
        
        # Same score and total CVEs, different recent CVEs
        if (cna1.get('overall_average_score') == cna2.get('overall_average_score') and 
                cna1.get('total_cves') == cna2.get('total_cves') and
                cna1.get('recent_cves_count') != cna2.get('recent_cves_count')):
            cve_count_tie_examples.append((i, cna1, cna2))
            if len(cve_count_tie_examples) >= 2:
                break
    
    for i in range(len(sorted_cna_summary) - 1):
        cna1 = sorted_cna_summary[i]
        cna2 = sorted_cna_summary[i + 1]
        
        # Same score, total CVEs, and recent CVEs - alphabetical sorting
        if (cna1.get('overall_average_score') == cna2.get('overall_average_score') and 
                cna1.get('total_cves') == cna2.get('total_cves') and
                cna1.get('recent_cves_count') == cna2.get('recent_cves_count')):
            recent_cve_tie_examples.append((i, cna1, cna2))
            if len(recent_cve_tie_examples) >= 2:
                break
    
    # Print examples of tie-breaking
    if score_tie_examples:
        print("\nExample of TIE-BREAKER 1 (total CVEs):\n")
        idx, cna1, cna2 = score_tie_examples[0]
        print(f"Rank {idx+1}: {cna1.get('shortName')} - Score: {cna1.get('overall_average_score')}, CVEs: {cna1.get('total_cves')}")
        print(f"Rank {idx+2}: {cna2.get('shortName')} - Score: {cna2.get('overall_average_score')}, CVEs: {cna2.get('total_cves')}")
        print("Same score, different total CVEs -> Higher CVE count ranked better")
    
    if cve_count_tie_examples:
        print("\nExample of TIE-BREAKER 2 (recent CVEs):\n")
        idx, cna1, cna2 = cve_count_tie_examples[0]
        print(f"Rank {idx+1}: {cna1.get('shortName')} - Score: {cna1.get('overall_average_score')}, Total CVEs: {cna1.get('total_cves')}, Recent: {cna1.get('recent_cves_count')}")
        print(f"Rank {idx+2}: {cna2.get('shortName')} - Score: {cna2.get('overall_average_score')}, Total CVEs: {cna2.get('total_cves')}, Recent: {cna2.get('recent_cves_count')}")
        print("Same score and total CVEs, different recent CVEs -> More recent activity ranked better")
    
    if recent_cve_tie_examples:
        print("\nExample of TIE-BREAKER 3 (alphabetical):\n")
        idx, cna1, cna2 = recent_cve_tie_examples[0]
        print(f"Rank {idx+1}: {cna1.get('shortName')} - Score: {cna1.get('overall_average_score')}, CVEs: {cna1.get('total_cves')}, Recent: {cna1.get('recent_cves_count')}")
        print(f"Rank {idx+2}: {cna2.get('shortName')} - Score: {cna2.get('overall_average_score')}, CVEs: {cna2.get('total_cves')}, Recent: {cna2.get('recent_cves_count')}")
        print(f"Same on all metrics -> Alphabetical sorting ({cna1.get('shortName')} before {cna2.get('shortName')})")
    
    # Verify key CNAs we're interested in
    key_cnas = ["ProgressSoftware", "mitre", "debian", "Linux"]
    print("\n" + "=" * 80)
    print("RANKING OF KEY CNAs")
    print("=" * 80)
    print("{:<5} {:<25} {:<10} {:<10} {:<10} {:<10}".format(
        "Rank", "CNA", "Score", "Total CVEs", "Recent CVEs", "Percentile"
    ))
    print("-" * 80)
    
    for cna_name in key_cnas:
        for i, cna in enumerate(sorted_cna_summary):
            if cna.get('shortName') == cna_name:
                print("{:<5} {:<25} {:<10.2f} {:<10} {:<10} {:<10.1f}".format(
                    i+1, 
                    cna_name, 
                    cna.get('overall_average_score', 0),
                    cna.get('total_cves', 0),
                    cna.get('recent_cves_count', 0),
                    ((len(sorted_cna_summary) - i) / len(sorted_cna_summary)) * 100
                ))
                break
    
    from run_pipeline import generate_individual_cna_jsons
    generated_count, ranking_map = generate_individual_cna_jsons(
        cve_records=filtered_cve_records,
        cna_scorecards=cna_outputs,
        sorted_active_cnas=sorted_active_cnas,
        cna_metadata=cna_metadata,
        trend_periods=trend_periods
    )

    print(f"Generated individual CNA JSON files in {os.path.join(os.path.dirname(__file__), '..', 'web', 'data', 'cna')}")

    # Generate combined CNA rankings file for the web interface
    print("\nGenerating combined CNA rankings file...")
    
    # Helper function to map CVE-derived CNA names to official CNA names
    def _map_to_official_cna_name(cve_derived_name, official_cna_metadata):
        """Map CVE-derived CNA name to official CNA name from authoritative source."""
        if not official_cna_metadata:
            return cve_derived_name
        
        # Try exact match first
        if cve_derived_name in official_cna_metadata:
            return cve_derived_name
        
        # Try case-insensitive match
        for official_name in official_cna_metadata.keys():
            if official_name.lower() == cve_derived_name.lower():
                return official_name
        
        # Try normalized matching (remove spaces, hyphens, underscores)
        normalized_cve_name = cve_derived_name.lower().replace(' ', '').replace('-', '').replace('_', '')
        for official_name in official_cna_metadata.keys():
            normalized_official = official_name.lower().replace(' ', '').replace('-', '').replace('_', '')
            if normalized_official == normalized_cve_name:
                return official_name
        
        # Try suffix removal (e.g., "redhat-cnalr" -> "redhat")
        if '-' in cve_derived_name:
            base_name = cve_derived_name.split('-')[0]
            for official_name in official_cna_metadata.keys():
                if official_name.lower() == base_name.lower():
                    return official_name
        
        # Try common company rebrand patterns
        rebrand_map = {
            'facebook': 'Meta',
            'fb': 'Meta'
        }
        mapped_name = rebrand_map.get(cve_derived_name.lower())
        if mapped_name:
            for official_name in official_cna_metadata.keys():
                if official_name.lower() == mapped_name.lower():
                    return official_name
        
        # Try partial matching (for complex cases)
        cve_name_lower = cve_derived_name.lower()
        for official_name in official_cna_metadata.keys():
            official_name_lower = official_name.lower()
            if (cve_name_lower in official_name_lower or official_name_lower in cve_name_lower) and len(cve_name_lower) > 2:
                return official_name
        
        # If no match found, return original name (will be filtered out later)
        return cve_derived_name
    
    # Helper function to find CNA type from metadata with name variations
    def _find_cna_type_from_metadata(short_name, metadata_dict):
        """Try to find CNA type from metadata using various name matching strategies."""
        if not metadata_dict:
            return 'Unknown', ['Unknown']
        
        # Try exact match first
        for cna_short_name, meta in metadata_dict.items():
            if cna_short_name == short_name:
                types = meta.get('type', [])
                if types and len(types) > 0:
                    valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                    if valid_types:
                        return valid_types[0], valid_types
        
        # Try case-insensitive match
        for cna_short_name, meta in metadata_dict.items():
            if cna_short_name.lower() == short_name.lower():
                types = meta.get('type', [])
                if types and len(types) > 0:
                    valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                    if valid_types:
                        return valid_types[0], valid_types
        
        # Try name variations (remove spaces, handle common variations)
        normalized_name = short_name.lower().replace(' ', '').replace('-', '').replace('_', '')
        for cna_short_name, meta in metadata_dict.items():
            normalized_meta_name = cna_short_name.lower().replace(' ', '').replace('-', '').replace('_', '')
            if normalized_meta_name == normalized_name:
                types = meta.get('type', [])
                if types and len(types) > 0:
                    valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                    if valid_types:
                        return valid_types[0], valid_types
        
        # Try suffix removal patterns (e.g., "redhat-cnalr" -> "redhat")
        if '-' in short_name:
            base_name = short_name.split('-')[0]
            for cna_short_name, meta in metadata_dict.items():
                if cna_short_name.lower() == base_name.lower():
                    types = meta.get('type', [])
                    if types and len(types) > 0:
                        valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                        if valid_types:
                            return valid_types[0], valid_types
        
        # Try common company rebrand patterns
        rebrand_map = {
            'facebook': 'Meta',
            'fb': 'Meta'
        }
        mapped_name = rebrand_map.get(short_name.lower())
        if mapped_name:
            for cna_short_name, meta in metadata_dict.items():
                if cna_short_name.lower() == mapped_name.lower():
                    types = meta.get('type', [])
                    if types and len(types) > 0:
                        valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                        if valid_types:
                            return valid_types[0], valid_types
        
        # Try partial matching (pipeline name contains metadata name or vice versa)
        short_name_lower = short_name.lower()
        for cna_short_name, meta in metadata_dict.items():
            meta_name_lower = cna_short_name.lower()
            if (short_name_lower in meta_name_lower or meta_name_lower in short_name_lower) and len(short_name_lower) > 2:
                types = meta.get('type', [])
                if types and len(types) > 0:
                    valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                    if valid_types:
                        return valid_types[0], valid_types
        
        # If no match found, return Unknown
        return 'Unknown', ['Unknown']
    
    # Transform data to match web interface expectations using official CNA names
    web_formatted_cnas = []
    
    for i, cna_info in enumerate(sorted_cna_summary):
        cve_derived_name = cna_info.get('shortName', '')
        
        # Map CVE-derived name to official CNA name
        official_name = _map_to_official_cna_name(cve_derived_name, official_cna_metadata)
        
        # Only include CNAs that exist in the official list
        if official_name not in official_cna_metadata:
            print(f"Skipping CNA '{cve_derived_name}' - not found in official CNA list")
            continue
        
        short_name = official_name  # Use official name as primary
        
        # Determine if this CNA is active (has recent CVEs) or inactive
        recent_cves_count = cna_info.get('recent_cves_count', 0)
        is_active = recent_cves_count > 0
        
        # Get proper tied ranking data from ranking_map (created by generate_individual_cna_jsons)
        ranking_data = ranking_map.get(cve_derived_name, {})
        cna_rank = ranking_data.get('rank') if is_active else None
        cna_percentile = ranking_data.get('percentile') if is_active else None
        active_cna_count = ranking_data.get('active_cna_count', len(sorted_active_cnas))
        
        # Handle MITRE special case - always assign as "Program" type
        if short_name.lower() == 'mitre':
            primary_type, types_array = 'Program', ['Program']
        else:
            # Use official metadata for CNA type lookup
            if official_cna_metadata and short_name in official_cna_metadata:
                official_meta = official_cna_metadata[short_name]
                types = official_meta.get('type', [])
                if types and len(types) > 0:
                    valid_types = [t for t in types if t and t.strip() and t.strip().upper() != 'N/A']
                    if valid_types:
                        primary_type, types_array = valid_types[0], valid_types
                    else:
                        primary_type, types_array = 'Unknown', ['Unknown']
                else:
                    primary_type, types_array = 'Unknown', ['Unknown']
            else:
                primary_type, types_array = 'Unknown', ['Unknown']
        
        # Use official metadata for organization details
        official_meta = official_cna_metadata.get(short_name, {})
        
        web_cna = {
            "shortName": short_name,
            "organizationName": official_meta.get('organizationName', short_name),
            "cnaType": primary_type,
            "cnaTypes": types_array,
            "rank": cna_rank,  # Use proper tied ranking data
            "active_cna_count": active_cna_count,  # Use count from ranking data
            "percentile": cna_percentile,  # Use percentile from tied ranking calculation
            "total_cves": cna_info.get('total_cves', 0),
            "recent_cves": cna_info.get('recent_cves_count', 0),
            "is_active": is_active,  # Flag to indicate active vs inactive status
            "scores": {
                "overall_average_score": cna_info.get('overall_average_score', 0),
                "foundational_completeness": cna_info.get('percent_foundational_completeness', 0),
                "root_cause_analysis": cna_info.get('percent_root_cause_analysis', 0),
                "software_identification": cna_info.get('percent_software_identification', 0),
                "severity_and_impact": cna_info.get('percent_severity_and_impact', 0),
                "patchinfo": cna_info.get('percent_patchinfo', 0)
            },
            "trend": cna_info.get('trend', {
                "direction": "steady",
                "description": "No trend data available",
                "monthly_data": []
            })
        }
        
        # Add official metadata
        web_cna.update({
            "scope": official_meta.get('scope', ''),
            "advisories": official_meta.get('advisories', []),
            "officialCnaID": official_meta.get('cnaID', ''),
            "country": official_meta.get('country', ''),
            "disclosurePolicy": official_meta.get('disclosurePolicy', [])
        })
        
        # Only include active CNAs (with recent CVEs > 0) in cna_combined.json
        # This ensures peer average calculations are based on meaningful comparisons
        if is_active:
            web_formatted_cnas.append(web_cna)
    
    write_json(web_formatted_cnas, "cna_combined.json")
    print(f"Generated cna_combined.json with {len(web_formatted_cnas)} CNAs for rankings page")
    
    # Generate cna_summary.json for completeness page CNA search functionality
    print("\nGenerating cna_summary.json for completeness page...")
    cna_summary_list = []
    for cna_info in sorted_cna_summary:
        summary_entry = {
            "cnaId": cna_info.get('cnaId', ''),
            "shortName": cna_info.get('shortName', ''),
            "overallScore": cna_info.get('overallScore', 0),
            "grade": cna_info.get('grade', ''),
            "previousPeriodCveCount": cna_info.get('previousPeriodCveCount', 0),
            "cveCount": cna_info.get('cveCount', 0),
            "type": cna_info.get('type', 'Unspecified'),
            "trend": cna_info.get('trend', {}).get('direction', 'steady')
        }
        cna_summary_list.append(summary_entry)
    
    write_json(cna_summary_list, "cna_summary.json")
    print(f"Generated cna_summary.json with {len(cna_summary_list)} CNAs")
    
    # Skip generating cna_scorecards.json - analysis shows it's loaded but never actually used
    # The completeness pages load this file but the scorecards parameter is never used in selectCNA function
    print("\nSkipping cna_scorecards.json generation - file loaded but never used by web interface")

    # Generate field utilization data with CNA ScoreCard highlighting
    print("\nGenerating field utilization data with CNA ScoreCard highlighting...")
    field_utilization_data = compute_field_utilization(filtered_cve_records, FIELD_LIST)
    
    # Enhance field utilization data with CNA ScoreCard categories and metadata
    enhanced_field_data = []
    for field_data in field_utilization_data:
        field_name = field_data['field']
        
        # Find the field metadata from CANONICAL_FIELDS
        field_metadata = next((f for f in CANONICAL_FIELDS if f['field'] == field_name), {})
        
        # Create enhanced field entry
        enhanced_entry = {
            'field': field_name,
            'percent': field_data['cna_percent'],  # Use cna_percent as percent for compatibility
            'unique_cnas': field_data['unique_cnas'],
            'importance': field_metadata.get('importance', 'Medium'),
            'description': field_metadata.get('description', ''),
            'cna_scorecard_category': field_metadata.get('cna_scorecard_category', None)
        }
        enhanced_field_data.append(enhanced_entry)
    
    # Write enhanced field utilization data
    write_json(enhanced_field_data, "field_utilization.json")
    print(f"Generated field utilization data with {len(enhanced_field_data)} fields")
    
    # Generate individual CNA field utilization files
    print("\nGenerating individual CNA field utilization files...")
    individual_cna_data = compute_individual_cna_field_utilization(filtered_cve_records, FIELD_LIST)
    
    # Write individual CNA field utilization files to completeness directory
    completeness_dir = "../web/data/completeness"
    os.makedirs(completeness_dir, exist_ok=True)
    
    for cna_short_name, utilization_data in individual_cna_data.items():
        # Sanitize filename to handle special characters but keep it readable
        safe_filename = "".join(c for c in cna_short_name if c.isalnum() or c in ('-', '_', '.')).rstrip()
        if not safe_filename:  # If all characters were removed, use a fallback
            safe_filename = "unknown_cna"
        
        filename = f"{safe_filename}_completeness.json"
        filepath = os.path.join(completeness_dir, filename)
        
        with open(filepath, 'w') as f:
            json.dump(utilization_data, f, indent=2)
    
    print(f"Generated {len(individual_cna_data)} individual CNA field utilization files in {completeness_dir}")
    
    # Write summary card info (as before)
    summary = {
        "analysis_period_start": current_start_str,
        "analysis_period_end": current_end_str,
        "cve_count": len(filtered_cve_records),
        "cna_count": len(cna_outputs)
    }
    write_json(summary, "completeness_summary.json")
    print(f"\nPipeline completed successfully!")
    print(f"Generated {len(cna_outputs)} CNA JSON files and summary.")

if __name__ == "__main__":
    main()
