name: CNA Completeness Analysis

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering
  
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  completeness-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run completeness analysis
      run: |
        cd cnacompletness
        python main.py
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add web/completeness/*.json
        git add cnacompletness/output/*.json || true
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update CNA completeness analysis data - $(date -u +%Y-%m-%d)"
          git push
        fi
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
        keep_files: true
